parameters:
    exception_to_status:
        InvalidArgumentException: 400
        App\Shared\Infrastructure\Persistence\ReadModel\Exception\NotFoundException: 404
        App\Shared\Domain\Exception\DateTimeException: 400
        Webmozart\Assert\InvalidArgumentException: 400
        App\Shared\Domain\Exception\FilterNotValidException: 400
services:
    _defaults:
        autowire: true 
        autoconfigure: true
        public: false

    _instanceof:
        App\Shared\Application\Command\CommandHandlerInterface:
            public: true
            tags:
                - { name: messenger.message_handler, bus: messenger.bus.command }

        App\Shared\Application\Query\QueryHandlerInterface:
            public: true
            tags:
                - { name: messenger.message_handler, bus: messenger.bus.query }
    
    App\:
        resource: '../src/App/*'
        exclude: '../src/App/**/{Migrations,EventSubscriber}'
    UI\:
        resource: '../src/UI/*'
        exclude: '../src/UI/**/{EventSubscriber}'
        
    
    UI\Http\Rest\Controller\:
        resource: '../src/UI/Http/Rest/Controller/*'
        tags: [ 'controller.service_arguments' ]

    App\Shared\Infrastructure\Bus\Command\MessengerCommandBus:
        arguments:
            - '@messenger.bus.command'

    App\Shared\Infrastructure\Bus\Query\MessengerQueryBus:
        arguments:
            - '@messenger.bus.query'

    UI\Cli\Command\:
        resource: '../src/UI/Cli/Command'
        
    
    UI\Http\Rest\EventSubscriber\ExceptionSubscriber:
        arguments:
            - "%kernel.environment%"
            - "%exception_to_status%"
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.exception' }
